export const SKILL_PACKS = {
  frontend: {
    label: 'Frontend Developer',
    icon: '🎨',
    skills: [
      { name: 'HTML5', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'CSS3', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'JavaScript', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'TypeScript', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'React', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Next.js', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Tailwind CSS', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Framer Motion', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Redux/Zustand', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Jest & Testing', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Webpack/Vite', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Git', category: 'tools', level: 'beginner', progress: 0 },
    ]
  },
  backend: {
    label: 'Backend Developer',
    icon: '⚙️',
    skills: [
      { name: 'Node.js', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Express.js', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Python', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'REST APIs', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'GraphQL', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'PostgreSQL', category: 'database', level: 'beginner', progress: 0 },
      { name: 'MongoDB', category: 'database', level: 'beginner', progress: 0 },
      { name: 'Redis', category: 'database', level: 'beginner', progress: 0 },
      { name: 'Docker', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'JWT/OAuth', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Prisma/Sequelize', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Git', category: 'tools', level: 'beginner', progress: 0 },
    ]
  },
  fullstack: {
    label: 'Full-Stack Developer',
    icon: '🚀',
    skills: [
      { name: 'HTML/CSS', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'JavaScript', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'TypeScript', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'React', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Next.js', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Tailwind CSS', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Node.js', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Express.js', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'REST APIs', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'MongoDB', category: 'database', level: 'beginner', progress: 0 },
      { name: 'PostgreSQL', category: 'database', level: 'beginner', progress: 0 },
      { name: 'Firebase', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Docker', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Git & GitHub', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Vercel/Netlify', category: 'tools', level: 'beginner', progress: 0 },
    ]
  },
  mobile: {
    label: 'Mobile Developer',
    icon: '📱',
    skills: [
      { name: 'React Native', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Expo', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Flutter/Dart', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'JavaScript', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'TypeScript', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'React Navigation', category: 'frontend', level: 'beginner', progress: 0 },
      { name: 'Firebase', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'REST APIs', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'AsyncStorage/SQLite', category: 'database', level: 'beginner', progress: 0 },
      { name: 'Push Notifications', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'App Store Deployment', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Git', category: 'tools', level: 'beginner', progress: 0 },
    ]
  },
  devops: {
    label: 'DevOps Engineer',
    icon: '☁️',
    skills: [
      { name: 'Linux', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Bash Scripting', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Docker', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Kubernetes', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'AWS', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Terraform', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'CI/CD (GitHub Actions)', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Nginx', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Prometheus/Grafana', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Python', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'Networking (TCP/DNS)', category: 'other', level: 'beginner', progress: 0 },
      { name: 'Git', category: 'tools', level: 'beginner', progress: 0 },
    ]
  },
  ml: {
    label: 'ML / Data Science',
    icon: '🤖',
    skills: [
      { name: 'Python', category: 'backend', level: 'beginner', progress: 0 },
      { name: 'NumPy', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Pandas', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Matplotlib/Seaborn', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Scikit-Learn', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'TensorFlow/PyTorch', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'SQL', category: 'database', level: 'beginner', progress: 0 },
      { name: 'Statistics & Probability', category: 'other', level: 'beginner', progress: 0 },
      { name: 'Linear Algebra', category: 'other', level: 'beginner', progress: 0 },
      { name: 'NLP Basics', category: 'other', level: 'beginner', progress: 0 },
      { name: 'Jupyter Notebooks', category: 'tools', level: 'beginner', progress: 0 },
      { name: 'Git', category: 'tools', level: 'beginner', progress: 0 },
    ]
  },
};
